/**
 * CTO AI — Project Memory ライター（task-101）
 *
 * 役割:
 *   SpecAnalysis の結果を target-project の
 *   docs/project_memory/ ディレクトリにMarkdownファイルとして書き出す。
 *
 * 書き出すファイル:
 *   goal.md               — プロジェクトの目的
 *   design_philosophy.md  — 設計思想
 *   mvp_scope.md          — MVPスコープ
 *   gap_analysis.md       — 不足情報一覧（要確認事項）
 *   external_services.md  — 外部サービス・課金情報
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import type { SpecAnalysis } from './specAnalyzer.js'
import { commitGeneratedDocs } from './commitGeneratedDocs.js'

export interface ProjectMemoryWriteResult {
  targetDir: string
  writtenFiles: string[]
  readinessScore: number
  readinessReason: string
  mustResolveGaps: number
}

/**
 * Project Memory を target-project に書き出す
 *
 * @param analysis  specAnalyzer の出力
 * @param targetProjectRoot  target-project のルートパス（絶対パス）
 */
export function writeProjectMemory(
  analysis: SpecAnalysis,
  targetProjectRoot: string,
): ProjectMemoryWriteResult {
  const memoryDir = path.resolve(targetProjectRoot, 'docs', 'project_memory')
  mkdirSync(memoryDir, { recursive: true })

  const writtenFiles: string[] = []

  // ── goal.md ──────────────────────────────────────────────
  const goalContent = `# Goal

${analysis.goal}

---

## ターゲットユーザー

${analysis.targetUsers.map(u => `- ${u}`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'goal.md'), goalContent)
  writtenFiles.push('docs/project_memory/goal.md')

  // ── design_philosophy.md ─────────────────────────────────
  const philosophyContent = `# Design Philosophy

${analysis.designPhilosophy.map((p, i) => `${i + 1}. **${p}**`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'design_philosophy.md'), philosophyContent)
  writtenFiles.push('docs/project_memory/design_philosophy.md')

  // ── mvp_scope.md ─────────────────────────────────────────
  const mvpContent = `# MVP Scope

## 概要

${analysis.mvpScope.description}

## 含む機能

${analysis.mvpScope.includedFeatures.map(f => `- ${f}`).join('\n')}

## 含まない機能（Phase 2以降）

${analysis.mvpScope.excludedFeatures.map(f => `- ${f}`).join('\n')}

## 技術スタック

${analysis.techStack.map(t => `- ${t}`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'mvp_scope.md'), mvpContent)
  writtenFiles.push('docs/project_memory/mvp_scope.md')

  // ── gap_analysis.md ──────────────────────────────────────
  const mustResolveGaps = analysis.gaps.filter(g => g.severity === 'must_resolve')
  const shouldResolveGaps = analysis.gaps.filter(g => g.severity === 'should_resolve')
  const optionalGaps = analysis.gaps.filter(g => g.severity === 'optional')

  const gapContent = `# Gap Analysis

開発開始前に確認・決定が必要な事項の一覧です。

## 準備スコア: ${analysis.readinessScore}/100

${analysis.readinessReason}

---

## 🔴 必須対応（must_resolve）

${mustResolveGaps.length === 0 ? '特になし' : mustResolveGaps.map(g => `### ${g.description}
- カテゴリ: ${g.category}
- 提案: ${g.suggestion}
`).join('\n')}

## 🟡 対応推奨（should_resolve）

${shouldResolveGaps.length === 0 ? '特になし' : shouldResolveGaps.map(g => `### ${g.description}
- カテゴリ: ${g.category}
- 提案: ${g.suggestion}
`).join('\n')}

## 🔵 任意対応（optional）

${optionalGaps.length === 0 ? '特になし' : optionalGaps.map(g => `### ${g.description}
- カテゴリ: ${g.category}
- 提案: ${g.suggestion}
`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'gap_analysis.md'), gapContent)
  writtenFiles.push('docs/project_memory/gap_analysis.md')

  // ── external_services.md ─────────────────────────────────
  const servicesContent = `# External Services

開発・運用に必要な外部サービス一覧です。

⚠️ 課金が発生するサービスの追加はCEO承認が必要です。

${analysis.requiredExternalServices.map(s => `## ${s.name}

- 用途: ${s.purpose}
- 課金: ${s.hasCost ? '**あり（CEO承認必要）**' : 'なし（無料）'}
`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'external_services.md'), servicesContent)
  writtenFiles.push('docs/project_memory/external_services.md')

  // CTO AIが機械的に生成したドキュメントをその場でcommitする。
  // uncommittedのまま残すと、直後にauto-startされる実装JobのFile Change Guardが
  // これらを誤って「Taskによる変更」として検出し、allowedPaths外として誤blockする。
  commitGeneratedDocs(targetProjectRoot, writtenFiles, 'chore(cto-ai): update project memory docs')

  return {
    targetDir: memoryDir,
    writtenFiles,
    readinessScore: analysis.readinessScore,
    readinessReason: analysis.readinessReason,
    mustResolveGaps: mustResolveGaps.length,
  }
}

// ────────────────────────────────────────────────────────────
// ヘルパー
// ────────────────────────────────────────────────────────────

function writeFile(filePath: string, content: string): void {
  writeFileSync(filePath, content, 'utf-8')
}
