/**
 * CTO AI — Project Memory ライター（task-101）
 *
 * 役割:
 *   SpecAnalysis の結果を target-project の
 *   docs/project_memory/ ディレクトリにMarkdownファイルとして書き出す。
 *
 * 書き出すファイル:
 *   goal.md               — プロジェクトの目的
 *   design_philosophy.md  — 設計思想
 *   mvp_scope.md          — MVPスコープ
 *   gap_analysis.md       — 不足情報一覧（要確認事項）
 *   external_services.md  — 外部サービス・課金情報
 *   project_definition.json — authoritative Project Definition metadata
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import type { SpecAnalysis } from './specAnalyzer.js'
import { commitGeneratedDocs } from './commitGeneratedDocs.js'
import { buildSpecTextFromProjectDefinition, computeProjectDefinitionHash } from './projectDefinitionAnalysis.js'

export interface ProjectMemoryWriteResult {
  targetDir: string
  writtenFiles: string[]
  readinessScore: number
  readinessReason: string
  mustResolveGaps: number
  definitionHash: string
  constraintsHash: string
}

export interface ProjectMemoryWriteOptions {
  canonicalDefinitionText?: string
}

/**
 * Project Memory を target-project に書き出す
 *
 * @param analysis  specAnalyzer の出力
 * @param targetProjectRoot  target-project のルートパス（絶対パス）
 */
export function writeProjectMemory(
  analysis: SpecAnalysis,
  targetProjectRoot: string,
  options: ProjectMemoryWriteOptions = {},
): ProjectMemoryWriteResult {
  const memoryDir = path.resolve(targetProjectRoot, 'docs', 'project_memory')
  mkdirSync(memoryDir, { recursive: true })

  const writtenFiles: string[] = []
  const generatedAt = new Date().toISOString()
  const canonicalDefinitionText = options.canonicalDefinitionText ?? buildSpecTextFromProjectDefinition({
    goal: analysis.goal,
    designPhilosophy: analysis.designPhilosophy,
  })
  const definitionHash = computeProjectDefinitionHash(canonicalDefinitionText)
  const structuredConstraints = canonicalizeStructuredConstraints(analysis.structuredConstraints)
  const constraintsHash = computeProjectDefinitionHash(JSON.stringify(structuredConstraints))

  // ── goal.md ──────────────────────────────────────────────
  const goalContent = `# Goal

${analysis.goal}

---

## ターゲットユーザー

${analysis.targetUsers.map(u => `- ${u}`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'goal.md'), goalContent)
  writtenFiles.push('docs/project_memory/goal.md')

  // ── design_philosophy.md ─────────────────────────────────
  const philosophyContent = `# Design Philosophy

${analysis.designPhilosophy.map((p, i) => `${i + 1}. **${p}**`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'design_philosophy.md'), philosophyContent)
  writtenFiles.push('docs/project_memory/design_philosophy.md')

  // ── mvp_scope.md ─────────────────────────────────────────
  const mvpContent = `# MVP Scope

## 概要

${analysis.mvpScope.description}

## 含む機能

${analysis.mvpScope.includedFeatures.map(f => `- ${f}`).join('\n')}

## 含まない機能（Phase 2以降）

${analysis.mvpScope.excludedFeatures.map(f => `- ${f}`).join('\n')}

## 技術スタック

${analysis.techStack.map(t => `- ${t}`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'mvp_scope.md'), mvpContent)
  writtenFiles.push('docs/project_memory/mvp_scope.md')

  // ── gap_analysis.md ──────────────────────────────────────
  const mustResolveGaps = analysis.gaps.filter(g => g.severity === 'must_resolve')
  const shouldResolveGaps = analysis.gaps.filter(g => g.severity === 'should_resolve')
  const optionalGaps = analysis.gaps.filter(g => g.severity === 'optional')
  // `decisionOwner: 'ai'`のGapはCEOへ質問されない代わりに、ここが後続AIへの唯一の引き継ぎ点に
  // なる。明示的に`'ai'`のときだけAI調査扱いとし、欠落・解釈不能はCEO判断側へ倒す（CEO質問側と同じ判定）。
  const gapOwnerLabel = (g: SpecAnalysis['gaps'][number]): string =>
    g.decisionOwner === 'ai'
      ? 'AI調査で解決（既存repo/spec/testを調べて決める。CEOへは質問されない）'
      : 'CEO判断'

  const gapContent = `# Gap Analysis

開発開始前に確認・決定が必要な事項の一覧です。

## 準備スコア: ${analysis.readinessScore}/100

${analysis.readinessReason}

---

## 🔴 必須対応（must_resolve）

${mustResolveGaps.length === 0 ? '特になし' : mustResolveGaps.map(g => `### ${g.description}
- カテゴリ: ${g.category}
- 解決の担当: ${gapOwnerLabel(g)}
- 提案: ${g.suggestion}
`).join('\n')}

## 🟡 対応推奨（should_resolve）

${shouldResolveGaps.length === 0 ? '特になし' : shouldResolveGaps.map(g => `### ${g.description}
- カテゴリ: ${g.category}
- 解決の担当: ${gapOwnerLabel(g)}
- 提案: ${g.suggestion}
`).join('\n')}

## 🔵 任意対応（optional）

${optionalGaps.length === 0 ? '特になし' : optionalGaps.map(g => `### ${g.description}
- カテゴリ: ${g.category}
- 解決の担当: ${gapOwnerLabel(g)}
- 提案: ${g.suggestion}
`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'gap_analysis.md'), gapContent)
  writtenFiles.push('docs/project_memory/gap_analysis.md')

  // ── external_services.md ─────────────────────────────────
  const servicesContent = `# External Services

開発・運用に必要な外部サービス一覧です。

⚠️ 課金が発生するサービスの追加はCEO承認が必要です。

${analysis.requiredExternalServices.map(s => `## ${s.name}

- 用途: ${s.purpose}
- 課金: ${s.hasCost ? '**あり（CEO承認必要）**' : 'なし（無料）'}
`).join('\n')}

---

*Generated by CTO AI on ${new Date().toISOString()}*
`
  writeFile(path.join(memoryDir, 'external_services.md'), servicesContent)
  writtenFiles.push('docs/project_memory/external_services.md')

  const projectDefinitionContent = JSON.stringify({
    definitionHash,
    generatedAt,
    goal: analysis.goal,
    designPhilosophy: analysis.designPhilosophy,
    structuredConstraints,
    constraintsHash,
    // CEOへ質問されなかった、AIが既存repo/spec/testを調査して解決すべき技術的不確実性。
    // 人が読む`gap_analysis.md`とは別に、後続AIが機械的に読めるようここへ構造化して残す
    // （markdownの日本語ラベルを読み手側でパースすると書き手と読み手が文字列結合してしまう。
    // 独立レビュー指摘、2026-09-06）。
    openTechnicalUncertainties: analysis.gaps
      .filter((g) => g.decisionOwner === 'ai')
      .map((g) => ({
        description: g.description,
        category: g.category,
        severity: g.severity,
        suggestion: g.suggestion,
      })),
  }, null, 2) + '\n'
  writeFile(path.join(memoryDir, 'project_definition.json'), projectDefinitionContent)
  writtenFiles.push('docs/project_memory/project_definition.json')

  // CTO AIが機械的に生成したドキュメントをその場でcommitする。
  // uncommittedのまま残すと、直後にauto-startされる実装JobのFile Change Guardが
  // これらを誤って「Taskによる変更」として検出し、allowedPaths外として誤blockする。
  commitGeneratedDocs(targetProjectRoot, writtenFiles, 'chore(cto-ai): update project memory docs')

  return {
    targetDir: memoryDir,
    writtenFiles,
    readinessScore: analysis.readinessScore,
    readinessReason: analysis.readinessReason,
    mustResolveGaps: mustResolveGaps.length,
    definitionHash,
    constraintsHash,
  }
}

// ────────────────────────────────────────────────────────────
// ヘルパー
// ────────────────────────────────────────────────────────────

function writeFile(filePath: string, content: string): void {
  writeFileSync(filePath, content, 'utf-8')
}

function canonicalizeStructuredConstraints(
  constraints: SpecAnalysis['structuredConstraints'],
): SpecAnalysis['structuredConstraints'] {
  return constraints.map((constraint) => ({
    kind: constraint.kind,
    value: Array.isArray(constraint.value) ? [...constraint.value] : constraint.value,
    description: constraint.description,
    sourceText: constraint.sourceText,
  }))
}
